### ISSUE TITLE
Ошибка в логах при сборке и запуске тестор - тесты проходят 

### ISSUE THREAD

**Issue by DVEfremov** [edu-xored/memorise#90]
```
08:37:16,151 INFO WebCrawler.info():337 - URL: http://www.eurosport.ru/football/champions-league/2016-2017/story_sto5959402.shtml
08:37:16,151 WARN WebCrawler.warn():412 - Unhandled exception while fetching http://www.eurosport.ru/football/champions-league/2016-2017/story_sto5959402.shtml: null
08:37:16,151 INFO WebCrawler.info():357 - Stacktrace: 
java.lang.NullPointerException
	at org.xored.edu.memorise.crawler.ActionsCrawler.tryFindMemo(ActionsCrawler.java:62)
	at org.xored.edu.memorise.crawler.ActionsCrawler.visit(ActionsCrawler.java:53)
	at edu.uci.ics.crawler4j.crawler.WebCrawler.processPage(WebCrawler.java:421)
	at edu.uci.ics.crawler4j.crawler.WebCrawler.run(WebCrawler.java:274)
	at java.lang.Thread.run(Thread.java:745)
08:37:21,775 INFO CrawlController.run():269 - It loo
```

**Comment by Rhymmor** [comment]
Связанно с задачей #87. Займусь после демо
